"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Branch = { id: string; name: string; shortName: string; isActive: boolean };
type Product = { id: number; model: string; name: string; sku: string | null; primaryImageUrl: string; isActive: boolean };
type Variant = { id: number; productId: number; color: string };
type Inventory = { id: number; variantId: number; size: string; branchId: string; quantity: number; lowStockThreshold: number; product: Product; variant: Variant; branch: Branch };
type Movement = { id: string; createdAt: string; type: string; size: string; quantityBefore: number; quantityDelta: number; quantityAfter: number; reason: string; actorName?: string; product: Product; variant: Variant; branch: Branch };
const qty = (value: number) => Math.max(1, Math.floor(Number.isFinite(value) ? value : 1));

export default function InventoryPanel() {
  const [branches, setBranches] = useState<Branch[]>([]); const [products, setProducts] = useState<Product[]>([]); const [variants, setVariants] = useState<Variant[]>([]); const [inventory, setInventory] = useState<Inventory[]>([]); const [movements, setMovements] = useState<Movement[]>([]); const [query, setQuery] = useState(""); const [notice, setNotice] = useState(""); const [tab, setTab] = useState<"existence" | "entry" | "transfer" | "movements" | "branches">("existence");
  const [form, setForm] = useState({ productId: "", variantId: "", size: "", branchId: "", originBranchId: "", destinationBranchId: "", quantity: 1, reason: "" });
  const load = async () => { const response = await fetch("/api/admin/inventory?q=" + encodeURIComponent(query), { cache: "no-store" }); const data = await response.json(); if (response.ok) { setBranches(data.branches || []); setProducts(data.products || []); setVariants(data.variants || []); setInventory(data.inventory || []); setMovements(data.movements || []); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const visibleProducts = useMemo(() => products.filter((product) => [product.model, product.name, product.sku].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase())), [products, query]);
  const chosenProduct = Number(form.productId); const chosenVariant = Number(form.variantId); const productVariants = variants.filter((variant) => variant.productId === chosenProduct); const productSizes = Array.from(new Set(inventory.filter((row) => row.variantId === chosenVariant).map((row) => row.size))).sort((a,b) => Number(a)-Number(b));
  const selectProduct = (value: string) => { const first = variants.find((variant) => variant.productId === Number(value)); setForm((current) => ({ ...current, productId: value, variantId: first ? String(first.id) : "", size: "" })); };
  const submit = async (action: "entry" | "adjustment" | "transfer", event: FormEvent) => { event.preventDefault(); const payload = action === "transfer" ? { action, productId: chosenProduct, variantId: chosenVariant, size: form.size, originBranchId: form.originBranchId, destinationBranchId: form.destinationBranchId, quantity: qty(form.quantity), reason: form.reason } : { action, productId: chosenProduct, variantId: chosenVariant, size: form.size, branchId: form.branchId, quantity: qty(form.quantity), reason: action === "adjustment" ? form.reason : "Entrada de mercancía" }; const response = await fetch("/api/admin/inventory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setNotice(data.error || "No se pudo guardar el movimiento."); return; } setNotice(action === "transfer" ? "Transferencia registrada." : action === "entry" ? "Entrada registrada." : "Ajuste registrado."); setForm((current) => ({ ...current, quantity: 1, reason: "" })); await load(); };
  const control = <><label>Buscar producto<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Modelo, SKU o nombre"/></label><label>Producto<select value={form.productId} onChange={(event) => selectProduct(event.target.value)}><option value="">Selecciona…</option>{visibleProducts.map((product) => <option value={product.id} key={product.id}>{product.model} · {product.name}</option>)}</select></label><label>Color<select value={form.variantId} onChange={(event) => setForm((current) => ({ ...current, variantId: event.target.value, size: "" }))}><option value="">Selecciona…</option>{productVariants.map((variant) => <option value={variant.id} key={variant.id}>{variant.color}</option>)}</select></label><label>Número<select value={form.size} onChange={(event) => setForm((current) => ({ ...current, size: event.target.value }))}><option value="">Selecciona…</option>{productSizes.map((size) => <option value={size} key={size}>#{size}</option>)}</select></label></>;
  const totalByBranch = (branchId: string) => inventory.filter((row) => row.branchId === branchId).reduce((sum, row) => sum + row.quantity, 0);
  const saveBranch = async (event: FormEvent<HTMLFormElement>, branch: Branch) => { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/admin/branches", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: branch.id, name: values.get("name"), shortName: values.get("shortName"), address: values.get("address"), phone: values.get("phone"), isActive: values.get("isActive") === "on" }) }); if (!response.ok) { setNotice("No se pudo actualizar la sucursal."); return; } setNotice("Sucursal actualizada."); await load(); };
  return <main className="admin-page inventory-page"><header className="admin-header"><Link className="brand" href="/admin"><span>RAMBER</span><small>OFICINA VIRTUAL</small></Link><Link href="/">Ver mi página</Link></header><section className="admin-intro"><p className="eyebrow wine">INVENTARIO REAL</p><h1>Sucursales y existencias</h1><p>El inventario se guarda por color, número y sucursal.</p></section><nav className="admin-module-nav"><Link href="/admin/productos">Catálogos</Link><button className={tab === "existence" ? "active" : ""} onClick={() => setTab("existence")}>Buscar existencia</button><button className={tab === "entry" ? "active" : ""} onClick={() => setTab("entry")}>Entrada</button><button className={tab === "transfer" ? "active" : ""} onClick={() => setTab("transfer")}>Transferencias</button><button className={tab === "movements" ? "active" : ""} onClick={() => setTab("movements")}>Movimientos</button><button className={tab === "branches" ? "active" : ""} onClick={() => setTab("branches")}>Sucursales</button></nav>{notice && <p className="admin-notice">{notice}</p>}
  {tab === "existence" && <section className="inventory-surface"><div className="inventory-toolbar"><label>Buscar existencia<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Modelo, SKU, nombre, color o talla"/></label><button onClick={() => void load()}>Buscar</button></div><div className="inventory-summary">{branches.map((branch) => <article key={branch.id}><span>{branch.shortName}</span><strong>{totalByBranch(branch.id)} pares</strong></article>)}<article><span>Poco inventario</span><strong>{inventory.filter((row) => row.quantity > 0 && row.quantity <= row.lowStockThreshold).length}</strong></article></div><div className="inventory-table">{inventory.map((row) => <article key={row.id}><img src={row.product.primaryImageUrl} alt=""/><div><b>{row.product.model} · {row.product.name}</b><span>{row.variant.color} · #{row.size}</span></div><strong className={row.quantity <= row.lowStockThreshold ? "low" : ""}>{row.quantity} pares</strong><small>{row.branch.shortName}</small></article>)}{!inventory.length && <p>No se encontró existencia todavía.</p>}</div></section>}
  {tab === "entry" && <section className="inventory-form"><h2>Entrada de mercancía</h2><form onSubmit={(event) => void submit("entry", event)}>{control}<label>Sucursal<select required value={form.branchId} onChange={(event) => setForm((current) => ({ ...current, branchId: event.target.value }))}><option value="">Selecciona…</option>{branches.filter((branch) => branch.isActive).map((branch) => <option value={branch.id} key={branch.id}>{branch.name}</option>)}</select></label><label>Pares que entran<div className="inventory-stepper"><button type="button" onClick={() => setForm((current) => ({ ...current, quantity: Math.max(1, current.quantity - 1) }))}>−</button><input type="number" min="1" value={form.quantity} onChange={(event) => setForm((current) => ({ ...current, quantity: qty(Number(event.target.value)) }))}/><button type="button" onClick={() => setForm((current) => ({ ...current, quantity: current.quantity + 1 }))}>+</button></div></label><button className="admin-save">Registrar entrada</button></form><hr/><h2>Ajustar inventario</h2><form onSubmit={(event) => void submit("adjustment", event)}>{control}<label>Sucursal<select required value={form.branchId} onChange={(event) => setForm((current) => ({ ...current, branchId: event.target.value }))}><option value="">Selecciona…</option>{branches.map((branch) => <option value={branch.id} key={branch.id}>{branch.name}</option>)}</select></label><label>Cantidad <input type="number" min="1" value={form.quantity} onChange={(event) => setForm((current) => ({ ...current, quantity: qty(Number(event.target.value)) }))}/></label><label>Motivo <select required value={form.reason} onChange={(event) => setForm((current) => ({ ...current, reason: event.target.value }))}><option value="">Selecciona…</option><option value="conteo físico">Conteo físico (+)</option><option value="-conteo físico">Conteo físico (−)</option><option value="daño">Daño (+)</option><option value="-daño">Daño (−)</option><option value="pérdida">Pérdida (−)</option><option value="error de captura">Error de captura (+)</option><option value="-error de captura">Error de captura (−)</option></select></label><button className="admin-save">Guardar ajuste</button></form></section>}
  {tab === "transfer" && <section className="inventory-form"><h2>Transferencia entre sucursales</h2><form onSubmit={(event) => void submit("transfer", event)}>{control}<label>Origen<select required value={form.originBranchId} onChange={(event) => setForm((current) => ({ ...current, originBranchId: event.target.value }))}><option value="">Selecciona…</option>{branches.map((branch) => <option value={branch.id} key={branch.id}>{branch.name}</option>)}</select></label><label>Destino<select required value={form.destinationBranchId} onChange={(event) => setForm((current) => ({ ...current, destinationBranchId: event.target.value }))}><option value="">Selecciona…</option>{branches.map((branch) => <option value={branch.id} key={branch.id}>{branch.name}</option>)}</select></label><label>Pares <input type="number" min="1" value={form.quantity} onChange={(event) => setForm((current) => ({ ...current, quantity: qty(Number(event.target.value)) }))}/></label><label>Nota <input value={form.reason} onChange={(event) => setForm((current) => ({ ...current, reason: event.target.value }))} placeholder="Opcional"/></label><button className="admin-save">Transferir</button></form></section>}
  {tab === "movements" && <section className="inventory-surface"><h2>Movimientos recientes</h2><div className="movement-list">{movements.map((movement) => <article key={movement.id}><time>{new Date(movement.createdAt).toLocaleString("es-MX")}</time><b>{movement.type}</b><span>{movement.product?.model} · {movement.variant?.color} · #{movement.size}</span><span>{movement.branch?.shortName} · {movement.quantityBefore} → <strong>{movement.quantityDelta > 0 ? "+" : ""}{movement.quantityDelta}</strong> → {movement.quantityAfter}</span><small>{movement.reason} · {movement.actorName || "Sistema / Migración"}</small></article>)}</div></section>}
  {tab === "branches" && <section className="inventory-surface"><h2>Sucursales</h2><div className="branch-cards">{branches.map((branch) => <form key={branch.id} onSubmit={(event) => void saveBranch(event, branch)}><article><h3>{branch.name}</h3><label>Nombre<input name="name" defaultValue={branch.name}/></label><label>Nombre corto<input name="shortName" defaultValue={branch.shortName}/></label><label>Dirección<input name="address" defaultValue={(branch as Branch & { address?: string }).address || ""}/></label><label>Teléfono<input name="phone" defaultValue={(branch as Branch & { phone?: string }).phone || ""}/></label><label><input name="isActive" type="checkbox" defaultChecked={branch.isActive}/> Sucursal activa</label><strong>{totalByBranch(branch.id)} pares registrados</strong><button>Guardar sucursal</button></article></form>)}</div></section>}</main>;
}
