"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";

type News = { id: number; title: string; body: string; imageUrl: string };
type Shoe = { id: number; category: "dama" | "infantil"; title: string; caption: string; imageUrl: string };
type Settings = Record<string, string>;
type Field = { key: string; label: string; multiline?: boolean };

const defaults: Settings = {
  heroEyebrow: "NUEVA COLECCIÓN", heroTitle: "Encuentra la bolsa que va contigo", heroImage: "/images/ramber-hero.png", heroPrimary: "Descubrir bolsas", heroSecondary: "Pedir cotización",
  opportunityImage: "/images/ramber-vende-sin-invertir.png", opportunityEyebrow: "OPORTUNIDAD RAMBER", opportunityTitle: "Tu estilo también puede darte ingresos.", opportunityLead: "Compra para ti, compra por mayoreo o vende por catálogo sin invertir en inventario.", opportunityOneTitle: "Menudeo", opportunityOneText: "Elige tu bolsa favorita desde $280.", opportunityTwoTitle: "Mayoreo", opportunityTwoText: "Mayoreo a partir de 2 bolsas.", opportunityThreeTitle: "Vende sin invertir", opportunityThreeText: "Próximamente: comparte el catálogo, toma pedidos y genera ingresos.",
  featuredEyebrow: "SELECCIÓN RAMBER", featuredTitle: "Nuevos modelos", featuredText: "Esta portada queda libre para mostrar promociones, lanzamientos y novedades.", productOneName: "Mochila para mujer", productOneCode: "RAM-001", productOneColor: "Café", productOneImage: "/images/producto-mochila-cafe.jpeg", productTwoName: "Bolsa casual", productTwoCode: "RAM-002", productTwoColor: "Negro o azul", productTwoImage: "/images/producto-bolsa-casual.jpeg", productThreeName: "Bolso elegante", productThreeCode: "RAM-003", productThreeColor: "Beige", productThreeImage: "/images/producto-bolso-beige.jpeg",
  footwearEyebrow: "COLECCIONES RAMBER", footwearTitle: "Calzado para toda la familia", footwearText: "Explora nuestros modelos para dama e infantil y pide el tuyo por WhatsApp.", womenShoesTitle: "Calzado para dama", womenShoesText: "Moda, comodidad y nuevos estilos.", womenShoesImage: "/images/ramber-shoe-tile.png", kidsShoesTitle: "Calzado infantil", kidsShoesText: "Modelos para niñas y niños.", kidsShoesImage: "",
  catalogEyebrow: "DESCARGAS", catalogTitle: "Descarga nuestros catálogos", catalogText: "Inspírate con nuestras colecciones y descubre lo nuevo.", catalogOneTitle: "Catálogo 1", catalogOneImage: "/images/catalog-wine.png", catalogTwoTitle: "Catálogo 2", catalogTwoImage: "/images/catalog-olive.png",
  quoteEyebrow: "COTIZACIÓN", quoteTitle: "¿Encontraste una bolsa que te gustó?", quoteText: "También puedes armar una cotización con varios modelos desde la sección Bolsas.",
  storesEyebrow: "VISÍTANOS", storesTitle: "Dos sucursales para atenderte", storesText: "Conoce nuestras tiendas RAMBER en Villahermosa, Tabasco.", crystalTitle: "Plaza Crystal", crystalImage: "/images/ramber-plaza-crystal.jpeg", crystal: "RAMBER Plaza Crystal · Villahermosa, Tabasco", americasTitle: "Plaza Las Américas", americasImage: "/images/ramber-plaza-las-americas.jpeg", americas: "RAMBER Plaza Las Américas · Villahermosa, Tabasco",
  footerTagline: "Estilo que te acompaña.", instagram: "@RAMBERCB", facebook: "RAMBER", whatsapp: "993 152 0202",
};

const sections: Array<{ title: string; fields: Field[] }> = [
  { title: "Portada", fields: [{ key: "heroEyebrow", label: "Texto pequeño" }, { key: "heroTitle", label: "Título principal", multiline: true }, { key: "heroPrimary", label: "Botón principal" }, { key: "heroSecondary", label: "Botón secundario" }] },
  { title: "Oportunidad / Mayoreo", fields: [{ key: "opportunityEyebrow", label: "Texto pequeño" }, { key: "opportunityTitle", label: "Título", multiline: true }, { key: "opportunityLead", label: "Descripción", multiline: true }, { key: "opportunityOneTitle", label: "Tarjeta 1 · título" }, { key: "opportunityOneText", label: "Tarjeta 1 · texto" }, { key: "opportunityTwoTitle", label: "Tarjeta 2 · título" }, { key: "opportunityTwoText", label: "Tarjeta 2 · texto" }, { key: "opportunityThreeTitle", label: "Tarjeta 3 · título" }, { key: "opportunityThreeText", label: "Tarjeta 3 · texto" }] },
  { title: "Nuevos modelos destacados", fields: [{ key: "featuredEyebrow", label: "Texto pequeño" }, { key: "featuredTitle", label: "Título" }, { key: "featuredText", label: "Pie de bloque", multiline: true }, ...[1, 2, 3].flatMap((number) => [{ key: `product${["One", "Two", "Three"][number - 1]}Name`, label: `Modelo ${number} · nombre` }, { key: `product${["One", "Two", "Three"][number - 1]}Code`, label: `Modelo ${number} · código` }, { key: `product${["One", "Two", "Three"][number - 1]}Color`, label: `Modelo ${number} · color` }]) ] },
  { title: "Calzado", fields: [{ key: "footwearEyebrow", label: "Texto pequeño" }, { key: "footwearTitle", label: "Título del bloque" }, { key: "footwearText", label: "Descripción", multiline: true }, { key: "womenShoesTitle", label: "Calzado dama · título" }, { key: "womenShoesText", label: "Calzado dama · pie" }, { key: "kidsShoesTitle", label: "Calzado infantil · título" }, { key: "kidsShoesText", label: "Calzado infantil · pie" }] },
  { title: "Catálogos y cotización", fields: [{ key: "catalogEyebrow", label: "Catálogos · texto pequeño" }, { key: "catalogTitle", label: "Catálogos · título" }, { key: "catalogText", label: "Catálogos · pie", multiline: true }, { key: "catalogOneTitle", label: "Nombre catálogo 1" }, { key: "catalogTwoTitle", label: "Nombre catálogo 2" }, { key: "quoteEyebrow", label: "Cotización · texto pequeño" }, { key: "quoteTitle", label: "Cotización · título" }, { key: "quoteText", label: "Cotización · pie", multiline: true }] },
  { title: "Sucursales y pie de página", fields: [{ key: "storesEyebrow", label: "Texto pequeño" }, { key: "storesTitle", label: "Título sucursales" }, { key: "storesText", label: "Descripción sucursales", multiline: true }, { key: "crystalTitle", label: "Sucursal 1 · nombre" }, { key: "crystal", label: "Sucursal 1 · ubicación" }, { key: "americasTitle", label: "Sucursal 2 · nombre" }, { key: "americas", label: "Sucursal 2 · ubicación" }, { key: "footerTagline", label: "Frase del pie de página" }, { key: "instagram", label: "Instagram" }, { key: "facebook", label: "Facebook" }, { key: "whatsapp", label: "WhatsApp" }] },
];
const images: Field[] = [
  { key: "heroImage", label: "Portada" }, { key: "opportunityImage", label: "Oportunidad / Mayoreo" }, { key: "productOneImage", label: "Modelo destacado 1" }, { key: "productTwoImage", label: "Modelo destacado 2" }, { key: "productThreeImage", label: "Modelo destacado 3" }, { key: "womenShoesImage", label: "Calzado dama" }, { key: "kidsShoesImage", label: "Calzado infantil" }, { key: "catalogOneImage", label: "Portada catálogo 1" }, { key: "catalogTwoImage", label: "Portada catálogo 2" }, { key: "crystalImage", label: "Sucursal Plaza Crystal" }, { key: "americasImage", label: "Sucursal Plaza Las Américas" },
];

export default function AdminPanel() {
  const [settings, setSettings] = useState<Settings>(defaults); const [news, setNews] = useState<News[]>([]); const [shoes, setShoes] = useState<Shoe[]>([]); const [notice, setNotice] = useState(""); const [uploading, setUploading] = useState(false); const [newItem, setNewItem] = useState({ title: "", body: "", imageUrl: "" }); const [newShoe, setNewShoe] = useState({ category: "dama", title: "", caption: "", imageUrl: "" });
  const set = (key: string, value: string) => setSettings((current) => ({ ...current, [key]: value }));
  const load = async () => { const [response, galleryResponse] = await Promise.all([fetch("/api/content", { cache: "no-store" }), fetch("/api/gallery", { cache: "no-store" })]); const [data, gallery] = await Promise.all([response.json(), galleryResponse.json()]); setSettings({ ...defaults, ...data.settings }); setNews(data.news || []); setShoes(gallery.items || []); };
  useEffect(() => { void load(); }, []);
  const save = async () => { await Promise.all(Object.entries(settings).map(([key, value]) => fetch("/api/content", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key, value }) }))); setNotice("Cambios guardados. Ya se ven en tu página."); };
  const upload = async (event: ChangeEvent<HTMLInputElement>, field: string) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setNotice("Subiendo imagen…"); const form = new FormData(); form.append("file", file); const response = await fetch("/api/media", { method: "POST", body: form }); const data = await response.json(); setUploading(false); if (!response.ok) { setNotice(data.error || "No se pudo subir la imagen."); return; } if (field === "news") setNewItem((current) => ({ ...current, imageUrl: data.url })); else if (field === "shoe") setNewShoe((current) => ({ ...current, imageUrl: data.url })); else set(field, data.url); setNotice("Imagen lista. Pulsa Guardar cambios al terminar."); };
  const publish = async (event: FormEvent) => { event.preventDefault(); const response = await fetch("/api/content", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(newItem) }); if (!response.ok) { setNotice("No se pudo publicar."); return; } setNewItem({ title: "", body: "", imageUrl: "" }); setNotice("Novedad publicada."); await load(); };
  const addShoe = async (event: FormEvent) => { event.preventDefault(); const response = await fetch("/api/gallery", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(newShoe) }); if (!response.ok) { setNotice("Completa categoría, nombre y foto."); return; } setNewShoe({ category: "dama", title: "", caption: "", imageUrl: "" }); setNotice("Foto agregada al álbum."); await load(); };
  const removeShoe = async (id: number) => { await fetch(`/api/gallery?id=${id}`, { method: "DELETE" }); await load(); };
  const remove = async (id: number) => { await fetch(`/api/content?id=${id}`, { method: "DELETE" }); await load(); }; const logout = async () => { await fetch("/api/admin/login", { method: "DELETE" }); window.location.href = "/"; };
  return <main className="admin-page"><header className="admin-header"><a className="brand" href="/"><span>RAMBER</span><small>ADMINISTRACIÓN</small></a><div><a href="/admin/productos">Catálogos</a><a href="/admin/inventario">Inventario</a><a href="/">Ver mi página</a><button className="admin-logout" onClick={() => void logout()}>Salir</button></div></header><section className="admin-intro"><p className="eyebrow wine">PANEL RAMBER</p><h1>Edita toda tu portada</h1><p>Cambia textos, fotos y cada pie de bloque. Al terminar, pulsa Guardar cambios.</p></section><nav className="admin-module-nav"><a href="/admin/productos">Calzado Dama</a><a href="/admin/productos?vista=infantil">Calzado Infantil</a><a href="/admin/productos?vista=ofertas">Ofertas</a><a href="/admin/inventario">Inventario</a><a href="/admin/inventario">Buscar existencia</a><a href="/admin/inventario">Entrada de mercancía</a><a href="/admin/inventario">Transferencias</a><a href="/admin/inventario">Movimientos</a><a href="/admin/inventario">Sucursales</a></nav>{notice && <p className="admin-notice">{notice}</p>}
    <section className="admin-grid">{sections.map((section) => <article className="admin-card" key={section.title}><h2>{section.title}</h2>{section.fields.map((field) => <label key={field.key}>{field.label}{field.multiline ? <textarea value={settings[field.key]} onChange={(event) => set(field.key, event.target.value)} /> : <input value={settings[field.key]} onChange={(event) => set(field.key, event.target.value)} />}</label>)}</article>)}<article className="admin-card admin-wide"><h2>Cambiar fotografías</h2><div className="admin-image-grid">{images.map((field) => <label key={field.key}>{field.label}<input type="file" accept="image/*" onChange={(event) => void upload(event, field.key)} />{settings[field.key] && <img className="admin-preview" src={settings[field.key]} alt="Vista previa"/>}</label>)}</div></article><article className="admin-card admin-wide"><button className="admin-save" disabled={uploading} onClick={() => void save()}>Guardar todos los cambios de la página</button></article><article className="admin-card admin-wide"><h2>Publicar una novedad</h2><form onSubmit={(event) => void publish(event)}><label>Título<input required value={newItem.title} onChange={(event) => setNewItem({ ...newItem, title: event.target.value })} /></label><label>Texto corto<textarea value={newItem.body} onChange={(event) => setNewItem({ ...newItem, body: event.target.value })} /></label><label>Foto<input type="file" accept="image/*" onChange={(event) => void upload(event, "news")} /></label>{newItem.imageUrl && <img className="admin-preview news-preview" src={newItem.imageUrl} alt="Vista previa"/>}<button className="admin-save" disabled={uploading}>Publicar en inicio</button></form></article></section><section className="admin-list"><h2>Novedades publicadas</h2>{news.length ? news.map((item) => <article key={item.id}>{item.imageUrl && <img src={item.imageUrl} alt=""/>}<div><strong>{item.title}</strong><p>{item.body}</p></div><button onClick={() => void remove(item.id)}>Eliminar</button></article>) : <p>Aún no has publicado novedades.</p>}</section></main>;
}
