"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
type Bag = { id: number; catalog: string; code: string; family: string; color: string; measurements: string; features: string; image: string };
const emptyForm = { code: "", family: "", color: "", measurements: "", features: "", image: "" };
export default function BagManager() {
  const [catalog, setCatalog] = useState<"1" | "2">("1");
  const [items, setItems] = useState<Bag[]>([]);
  const [notice, setNotice] = useState("");
  const [uploading, setUploading] = useState(false);
  const [editing, setEditing] = useState<number | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const load = async () => { const response = await fetch(`/api/admin/bags?catalog=${catalog}`, { cache: "no-store" }); const data = await response.json(); setItems(data.items || []); };
  useEffect(() => { void load(); }, [catalog]);
  const set = (key: keyof typeof emptyForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setNotice("Subiendo foto…"); const body = new FormData(); body.append("file", file); const response = await fetch("/api/media", { method: "POST", body }); const data = await response.json(); setUploading(false); if (!response.ok) { setNotice(data.error || "No se pudo subir la foto."); return; } set("image", data.url); setNotice("Foto lista. Revisa los datos y guarda."); };
  const openNew = () => { setForm(emptyForm); setEditing(null); setShowForm(true); setNotice(""); };
  const edit = (bag: Bag) => { setForm({ code: bag.code, family: bag.family, color: bag.color, measurements: bag.measurements, features: bag.features, image: bag.image }); setEditing(bag.id); setShowForm(true); setNotice(""); };
  const save = async (event: FormEvent) => { event.preventDefault(); const payload = { ...form, catalog, id: editing ?? undefined }; const response = await fetch("/api/admin/bags", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setNotice(data.error || "No se pudo guardar."); return; } setNotice(editing ? "Bolsa actualizada." : "Bolsa agregada al catálogo."); setShowForm(false); setEditing(null); setForm(emptyForm); await load(); };
  const remove = async (bag: Bag) => { if (!window.confirm(`¿Eliminar el modelo ${bag.code} · ${bag.color}?`)) return; const response = await fetch(`/api/admin/bags?id=${bag.id}`, { method: "DELETE" }); if (!response.ok) { setNotice("No se pudo eliminar."); return; } setNotice("Bolsa eliminada."); await load(); };
  const chooseCatalog = (next: "1" | "2") => { setCatalog(next); setShowForm(false); setEditing(null); setForm(emptyForm); };
  return <section className="product-admin">
    <div className="admin-intro"><p className="eyebrow wine">BOLSAS RAMBER</p><h2>Catálogo {catalog} · {items.length} bolsas</h2><p>Sube, edita o elimina las bolsas de cada catálogo. Se actualizan en tu página automáticamente.</p></div>
    <nav className="admin-module-nav"><button className={catalog === "1" ? "active" : ""} onClick={() => chooseCatalog("1")}>Catálogo 1</button><button className={catalog === "2" ? "active" : ""} onClick={() => chooseCatalog("2")}>Catálogo 2</button></nav>
    {notice && <p className="admin-notice">{notice}</p>}
    <div className="product-manager-head"><div><p className="eyebrow wine">CATÁLOGO {catalog}</p><h2>{items.length} bolsa{items.length === 1 ? "" : "s"}</h2></div><button className="admin-new-product" onClick={openNew}>+ Agregar bolsa</button></div>
    {showForm && <section className="product-editor"><div className="product-editor-heading"><div><p className="eyebrow wine">{editing ? "EDITAR BOLSA" : "NUEVA BOLSA"}</p><h2>{editing ? `Modelo ${form.code}` : "Agregar bolsa"}</h2></div><button type="button" onClick={() => setShowForm(false)}>Cerrar</button></div><form onSubmit={(event) => void save(event)}><section className="product-photo-editor"><div><h3>Fotografía</h3><p>Sube la foto principal de la bolsa.</p></div><label className="photo-upload">Subir fotografía<input type="file" accept="image/*" onChange={(event) => void upload(event)} disabled={uploading}/></label>{form.image && <div className="product-photo-strip"><article className="cover"><img src={form.image} alt="Vista previa"/></article></div>}</section><div className="product-form-grid"><label>Modelo <small>código</small><input required value={form.code} onChange={(event) => set("code", event.target.value)} placeholder="Ej. 4125"/></label><label>Familia <small>nombre del modelo</small><input required value={form.family} onChange={(event) => set("family", event.target.value)} placeholder="Ej. Aurora"/></label><label>Color<input required value={form.color} onChange={(event) => set("color", event.target.value)} placeholder="Ej. Negro"/></label><label>Medidas<input value={form.measurements} onChange={(event) => set("measurements", event.target.value)} placeholder="Largo 33 cm Ancho 13 cm Alto 17 cm"/></label><label className="product-form-wide">Características<textarea value={form.features} onChange={(event) => set("features", event.target.value)} placeholder="Un compartimento · Bolsa interior · Una asa"/></label></div><button className="admin-save" disabled={uploading}>{uploading ? "Subiendo…" : editing ? "Guardar cambios" : "Guardar bolsa"}</button></form></section>}
    <section className="admin-product-grid">{items.length ? items.map((bag) => <article key={bag.id}><img src={bag.image} alt={`${bag.family} ${bag.color}`}/><div className="admin-product-body"><p>MODELO {bag.code}</p><h2>{bag.family}</h2><span>{bag.color}</span><small>{bag.measurements}</small><div><button onClick={() => edit(bag)}>Editar</button><button className="danger" onClick={() => void remove(bag)}>Eliminar</button></div></div></article>) : <div className="admin-empty-products"><h2>Aún no hay bolsas</h2><p>Agrega la primera bolsa de este catálogo.</p></div>}</section>
  </section>;
}
