"use client";

import { useEffect, useMemo, useState } from "react";

type Category = "dama" | "infantil";
type Product = { id: number; category: Category; model: string; name: string; description: string; color: string; publicPrice: number; promoPrice: number | null; inOffer: boolean; primaryImageUrl: string; primaryImageZoom: number; primaryImageX: number; primaryImageY: number; sizes: Array<{ size: string; available: boolean }>; variants?: Array<{ color: string; sizes: Array<{ size: string; available: boolean }> }> };
const money = (value: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 }).format(value);

export default function ShoeAlbum({ category, offers = false }: { category?: Category; offers?: boolean }) {
  const [items, setItems] = useState<Product[]>([]);
  const [query, setQuery] = useState(""); const [color, setColor] = useState("all"); const [size, setSize] = useState("all"); const [onlyOffers, setOnlyOffers] = useState(offers);
  useEffect(() => { const search = offers ? "offers=1" : `category=${category}`; fetch(`/api/products?${search}`, { cache: "no-store" }).then((response) => response.json()).then((data) => setItems(data.items || [])).catch(() => undefined); }, [category, offers]);
  const title = offers ? "Ofertas RAMBER" : category === "dama" ? "Calzado para dama" : "Calzado infantil";
  const lead = offers ? "Modelos seleccionados con precio especial." : category === "dama" ? "Estilo, comodidad y diseño para cada ocasión." : "Diseños resistentes, suaves y pensados para cada aventura.";
  const hero = category === "dama" ? "/images/ramber-hero-dama.png" : "/images/ramber-hero-infantil.png";
  const colors = Array.from(new Set(items.flatMap((item) => item.variants?.map((variant) => variant.color) || [item.color]).filter(Boolean)));
  const sizes = Array.from(new Set(items.flatMap((item) => item.sizes.map((entry) => entry.size)))).sort((a, b) => Number(a) - Number(b));
  const filtered = useMemo(() => items.filter((item) => {
    const variantColors = item.variants?.map((variant) => variant.color) || [item.color]; const haystack = [item.model, item.name, item.description, item.color, item.category, ...variantColors, ...item.sizes.map((entry) => entry.size)].join(" ").toLowerCase();
    return (!query || haystack.includes(query.toLowerCase())) && (color === "all" || variantColors.includes(color)) && (size === "all" || item.sizes.some((entry) => entry.size === size && entry.available)) && (!onlyOffers || item.inOffer);
  }), [items, query, color, size, onlyOffers]);
  return <main className={`shoe-album-page premium-album ${offers ? "offers-page" : ""}`}>
    <header className="catalog-topbar"><a className="catalog-menu" href="/" aria-label="Volver al inicio">←</a><a className="catalog-brand" href="/"><span>RAMBER</span><small>CALZADOS Y BOLSAS</small></a><a className="catalog-cart" href="/bolsas" aria-label="Ver carrito">♧<b>0</b></a></header>
    <section className="catalog-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(255,250,244,.96) 0%, rgba(255,250,244,.82) 46%, rgba(255,250,244,.05) 100%), url(${hero})` }}><p>{offers ? "PRECIO ESPECIAL" : "COLECCIÓN RAMBER"}</p><h1>{title}</h1><i></i><span>{lead}</span></section>
    <section className="catalog-controls"><label className="catalog-search">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar modelos, tallas, colores…"/></label><button className="catalog-filter-button" onClick={() => document.getElementById("catalog-filters")?.classList.toggle("open")}>☷ <span>Filtros</span></button><div id="catalog-filters" className="catalog-filters"><label>Color<select value={color} onChange={(event) => setColor(event.target.value)}><option value="all">Todos los colores</option>{colors.map((entry) => <option key={entry} value={entry}>{entry}</option>)}</select></label><label>Talla<select value={size} onChange={(event) => setSize(event.target.value)}><option value="all">Todas las tallas</option>{sizes.map((entry) => <option key={entry} value={entry}>{entry}</option>)}</select></label></div><div className="catalog-chips"><button className={!onlyOffers ? "active" : ""} onClick={() => setOnlyOffers(false)}>⌁ Todos</button><button className={onlyOffers ? "active" : ""} onClick={() => setOnlyOffers(true)}>⌑ Ofertas</button>{colors.slice(0, 4).map((entry) => <button className={color === entry ? "active" : ""} key={entry} onClick={() => setColor(color === entry ? "all" : entry)}>{entry}</button>)}</div></section>
    <section className="catalog-list">{filtered.length ? filtered.map((item) => { const price = item.inOffer && item.promoPrice !== null ? item.promoPrice : item.publicPrice; return <a key={item.id} className="catalog-row-card" href={`/calzado/${item.category}/${item.id}`}><span className="catalog-row-image">{item.inOffer && <b>⌑ Oferta</b>}<img src={item.primaryImageUrl} alt={item.name} style={{ transform: `scale(${(item.primaryImageZoom ?? 100) / 100})`, transformOrigin: `${item.primaryImageX ?? 50}% ${item.primaryImageY ?? 50}%` }}/></span><span className="catalog-row-body"><small>MODELO</small><strong>{item.model || item.name}</strong><em>{item.name !== item.model ? item.name : item.description || item.color}</em><span className="catalog-sizes"><b>TALLAS</b>{item.sizes.map((entry) => <i className={!entry.available ? "out" : ""} key={entry.size}>{entry.size}</i>)}</span><span className="catalog-row-price">{item.inOffer && item.promoPrice !== null && <del>{money(item.publicPrice)}</del>}<b>{money(price)}</b></span><span className="catalog-details">Ver detalles&nbsp; ›</span></span></a>; }) : <div className="album-empty"><h2>{items.length ? "No encontramos modelos" : "Próximamente habrá modelos aquí"}</h2><p>{items.length ? "Prueba con otra búsqueda o filtro." : "En cuanto subas tus zapatos desde Admin aparecerán con este nuevo diseño."}</p></div>}</section>
    <nav className="mobile-catalog-nav"><a href="/">⌂<span>Inicio</span></a><a href="/bolsas">♧<span>Bolsas</span></a><a className={category === "dama" ? "active" : ""} href="/calzado-dama">♙<span>Dama</span></a><a className={category === "infantil" ? "active" : ""} href="/calzado-infantil">♧<span>Infantil</span></a><a className={offers ? "active" : ""} href="/ofertas">⌑<span>Ofertas</span></a></nav>
  </main>;
}
