"use client";
import Link from "next/link";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
type Category = "dama" | "infantil"; type DiscountType = "percentage" | "fixed"; type SizeStock = { size: string; quantity: number }; type Branch = { id: string; name: string; shortName: string }; type BranchStock = { size: string; branchId: string; quantity: number }; type Variant = { id: number; color: string; stocks: BranchStock[] };
type Product = { id: number; category: Category; model: string; sku: string | null; name: string; description: string; color: string; costPrice: number; publicPrice: number; promoPrice: number | null; inOffer: boolean; discountType: DiscountType | null; discountValue: number | null; isActive: boolean; primaryImageUrl: string; primaryImageZoom: number; primaryImageX: number; primaryImageY: number; sizes: SizeStock[]; variants: Variant[]; images: string[] };
type ProductForm = Omit<Product, "id" | "variants"> & { branchStocks: BranchStock[] };
const womenSizes = ["2", "2.5", "3", "3.5", "4", "4.5", "5", "5.5", "6", "6.5", "7"];
const kidsSizes = Array.from({ length: 20 }, (_, index) => String(12 + index * .5));
const money = (value: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 }).format(value);
const empty = (category: Category): ProductForm => ({ category, model: "", sku: "", name: "", description: "", color: "", costPrice: Number.NaN, publicPrice: Number.NaN, promoPrice: null, inOffer: false, discountType: "percentage", discountValue: 0, isActive: true, primaryImageUrl: "", primaryImageZoom: 100, primaryImageX: 50, primaryImageY: 50, sizes: [], branchStocks: [], images: [] });
export default function ProductManager() {
  const [tab, setTab] = useState<"dama" | "infantil" | "ofertas">("dama"); const [products, setProducts] = useState<Product[]>([]); const [branches, setBranches] = useState<Branch[]>([]); const [form, setForm] = useState<ProductForm>(empty("dama")); const [editing, setEditing] = useState<number | null>(null); const [showForm, setShowForm] = useState(false); const [uploading, setUploading] = useState(false); const [notice, setNotice] = useState("");
  const load = async () => { const response = await fetch("/api/admin/products", { cache: "no-store" }); const data = await response.json(); if (response.ok) setProducts(data.items || []); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); void fetch("/api/admin/branches").then((response) => response.json()).then((data) => setBranches(data.items || [])); const view = new URLSearchParams(window.location.search).get("vista"); if (view === "infantil" || view === "ofertas") setTab(view); }, 0); return () => window.clearTimeout(timer); }, []);
  const shown = useMemo(() => tab === "ofertas" ? products.filter((p) => p.inOffer) : products.filter((p) => p.category === tab), [products, tab]);
  const finalPrice = useMemo(() => { if (!form.inOffer || !form.discountType) return form.publicPrice; const value = Math.max(0, Number(form.discountValue || 0)); return form.discountType === "percentage" ? Math.max(0, Math.round(form.publicPrice * (100 - Math.min(100, value)) / 100)) : Math.max(0, form.publicPrice - value); }, [form]);
  const totalPairs = form.branchStocks.reduce((total, item) => total + item.quantity, 0);
  const set = <K extends keyof ProductForm>(key: K, value: ProductForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  const chooseTab = (next: "dama" | "infantil" | "ofertas") => { setTab(next); setShowForm(false); setEditing(null); setForm(empty(next === "infantil" ? "infantil" : "dama")); };
  const addSize = (size: string) => { if (!form.sizes.some((item) => item.size === size)) setForm((current) => ({ ...current, sizes: [...current.sizes, { size, quantity: 0 }], branchStocks: [...current.branchStocks, ...branches.map((branch, index) => ({ size, branchId: branch.id, quantity: index === 0 ? 1 : 0 }))] })); };
  const setQuantity = (size: string, branchId: string, quantity: number) => setForm((current) => ({ ...current, branchStocks: current.branchStocks.map((item) => item.size === size && item.branchId === branchId ? { ...item, quantity: Math.max(0, Math.floor(Number.isFinite(quantity) ? quantity : 0)) } : item) }));
  const removeSize = (size: string) => setForm((current) => ({ ...current, sizes: current.sizes.filter((item) => item.size !== size), branchStocks: current.branchStocks.filter((item) => item.size !== size) })); const selected = (size: string) => form.sizes.find((item) => item.size === size);
  const uploadFiles = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []); if (!files.length) return; setUploading(true); setNotice("Subiendo fotografías…"); const urls: string[] = []; for (const file of files) { const body = new FormData(); body.append("file", file); const response = await fetch("/api/media", { method: "POST", body }); const data = await response.json(); if (!response.ok) { setNotice(data.error || "No se pudo subir una foto."); setUploading(false); return; } urls.push(data.url); } setForm((current) => { const images = [...current.images, ...urls]; return { ...current, images, primaryImageUrl: current.primaryImageUrl || images[0] }; }); setUploading(false); setNotice("Fotos listas."); };
  const openNew = () => { const category = tab === "infantil" ? "infantil" : "dama"; setForm(empty(category)); setEditing(null); setShowForm(true); setNotice(""); };
  const edit = (product: Product) => { const fallback = product.inOffer ? Math.max(0, product.publicPrice - (product.promoPrice ?? product.publicPrice)) : 0; const variant = product.variants?.[0]; setForm({ ...product, color: variant?.color || product.color, sku: product.sku || "", discountType: product.discountType || "fixed", discountValue: product.discountValue ?? fallback, primaryImageZoom: product.primaryImageZoom ?? 100, primaryImageX: product.primaryImageX ?? 50, primaryImageY: product.primaryImageY ?? 50, sizes: product.sizes.map((item) => ({ ...item })), branchStocks: variant?.stocks?.map((item) => ({ size: item.size, branchId: item.branchId, quantity: item.quantity })) || [] }); setEditing(product.id); setShowForm(true); setNotice(""); };
  const makeCover = (url: string) => setForm((current) => ({ ...current, primaryImageUrl: url, primaryImageZoom: 100, primaryImageX: 50, primaryImageY: 50 }));
  const removeImage = (url: string) => setForm((current) => { const images = current.images.filter((image) => image !== url); const cover = current.primaryImageUrl === url; return { ...current, images, ...(cover ? { primaryImageUrl: images[0] || "", primaryImageZoom: 100, primaryImageX: 50, primaryImageY: 50 } : {}) }; });
  const save = async (event: FormEvent) => { event.preventDefault(); if (!form.images.length || !form.sizes.length) { setNotice("Agrega una foto y al menos una talla."); return; } const payload = { ...form, imageUrls: form.images, costPrice: Math.round(Number(form.costPrice)), publicPrice: Math.round(Number(form.publicPrice)), discountValue: form.inOffer ? Math.round(Number(form.discountValue)) : null }; const response = await fetch(editing ? "/api/admin/products/" + editing : "/api/admin/products", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setNotice(data.error || "No se pudo guardar."); return; } setNotice(editing ? "Producto actualizado." : "Producto agregado al catálogo."); setShowForm(false); setEditing(null); await load(); };
  const deactivate = async (product: Product) => { if (!window.confirm("¿Desactivar " + (product.name || product.model) + "? Ya no se verá públicamente.")) return; const response = await fetch("/api/admin/products/" + product.id, { method: "DELETE" }); if (!response.ok) { setNotice("No se pudo desactivar."); return; } setNotice("Producto desactivado."); await load(); };
  const sizes = form.category === "dama" ? womenSizes : kidsSizes; const title = tab === "dama" ? "Calzado Dama" : tab === "infantil" ? "Calzado Infantil" : "Ofertas";
  return <main className="admin-page product-admin"><header className="admin-header"><Link className="brand" href="/admin"><span>RAMBER</span><small>OFICINA VIRTUAL</small></Link><Link href="/">Ver mi página</Link></header><section className="admin-intro"><p className="eyebrow wine">CATÁLOGOS RAMBER</p><h1>Calzado y ofertas</h1><p>Sube un modelo con fotos, tallas, pares y precio.</p></section><nav className="admin-module-nav"><button className={tab === "dama" ? "active" : ""} onClick={() => chooseTab("dama")}>Calzado Dama</button><button className={tab === "infantil" ? "active" : ""} onClick={() => chooseTab("infantil")}>Calzado Infantil</button><button className={tab === "ofertas" ? "active" : ""} onClick={() => chooseTab("ofertas")}>Ofertas</button></nav>{notice && <p className="admin-notice">{notice}</p>}<section className="product-manager-head"><div><p className="eyebrow wine">{title}</p><h2>{shown.length} producto{shown.length === 1 ? "" : "s"}</h2></div><button className="admin-new-product" onClick={openNew}>+ Agregar producto</button></section>
  {showForm && <section className="product-editor"><div className="product-editor-heading"><div><p className="eyebrow wine">{editing ? "EDITAR PRODUCTO" : "NUEVO PRODUCTO"}</p><h2>{editing ? form.name || form.model || "Editar modelo" : "Agregar producto"}</h2></div><button type="button" onClick={() => setShowForm(false)}>Cerrar</button></div><form onSubmit={(event) => void save(event)}><section className="product-photo-editor"><div><h3>1. Fotografías</h3><p>Elige una portada y agrega las vistas que necesites.</p></div><label className="photo-upload">Subir fotografías<input type="file" accept="image/*" multiple onChange={(event) => void uploadFiles(event)} disabled={uploading}/></label><div className="product-photo-strip">{form.images.map((url) => <article className={form.primaryImageUrl === url ? "cover" : ""} key={url}><img src={url} alt="Vista previa"/><button type="button" onClick={() => makeCover(url)}>{form.primaryImageUrl === url ? "Portada" : "Usar portada"}</button><button type="button" className="remove-photo" onClick={() => removeImage(url)}>Quitar</button></article>)}</div>{form.primaryImageUrl && <section className="photo-crop-editor"><div className="photo-crop-preview"><img src={form.primaryImageUrl} alt="Previsualización de portada" style={{ transform: "scale(" + form.primaryImageZoom / 100 + ")", transformOrigin: form.primaryImageX + "% " + form.primaryImageY + "%" }}/></div><div><h3>Ajustar portada</h3><p>Acerca, aleja y mueve la foto. La original no se corta.</p><label>Zoom <output>{form.primaryImageZoom}%</output><input type="range" min="100" max="300" step="5" value={form.primaryImageZoom} onChange={(event) => set("primaryImageZoom", Number(event.target.value))}/></label><label>Izquierda / derecha<input type="range" min="0" max="100" value={form.primaryImageX} onChange={(event) => set("primaryImageX", Number(event.target.value))}/></label><label>Arriba / abajo<input type="range" min="0" max="100" value={form.primaryImageY} onChange={(event) => set("primaryImageY", Number(event.target.value))}/></label><button type="button" className="crop-reset" onClick={() => setForm((current) => ({ ...current, primaryImageZoom: 100, primaryImageX: 50, primaryImageY: 50 }))}>Restablecer encuadre</button></div></section>}</section>
    <div className="product-form-grid"><label>Categoría<select value={form.category} onChange={(event) => setForm((current) => ({ ...current, category: event.target.value as Category, sizes: [] }))}><option value="dama">Calzado Dama</option><option value="infantil">Calzado Infantil</option></select></label><label>Modelo <small>opcional si pones nombre</small><input value={form.model} onChange={(event) => set("model", event.target.value)} placeholder="Ej. 528"/></label><label>SKU <small>opcional</small><input value={form.sku || ""} onChange={(event) => set("sku", event.target.value)} placeholder="Ej. DAM-528"/></label><label>Nombre <small>opcional si pones modelo</small><input value={form.name} onChange={(event) => set("name", event.target.value)} placeholder="Ej. Sandalia plataforma"/></label><label>Color<input required value={form.color} onChange={(event) => set("color", event.target.value)} placeholder="Ej. Negro"/></label><label>Precio de costo<input required type="number" min="0" value={Number.isFinite(form.costPrice) ? form.costPrice : ""} onChange={(event) => set("costPrice", event.target.value === "" ? Number.NaN : Number(event.target.value))}/></label><label>Precio público<input required type="number" min="0" value={Number.isFinite(form.publicPrice) ? form.publicPrice : ""} onChange={(event) => set("publicPrice", event.target.value === "" ? Number.NaN : Number(event.target.value))}/></label><label className="product-form-wide">Descripción corta <small>opcional</small><textarea value={form.description} onChange={(event) => set("description", event.target.value)} placeholder="Material, estilo o detalles del modelo."/></label></div>
    <fieldset className="size-picker"><legend>2. Tallas y pares <span className="total-pairs">Total: {totalPairs} pares</span></legend><p>Toca una talla para seleccionarla. Después indica cuántos pares hay en cada sucursal.</p><div className="size-stock-grid">{sizes.map((size) => { const item = selected(size); return <article className={item ? "selected" : ""} key={size}><button type="button" className="size-toggle" onClick={() => addSize(size)}>{size}</button>{item && <div className="branch-size-stocks">{branches.map((branch) => { const stock = form.branchStocks.find((entry) => entry.size === size && entry.branchId === branch.id)?.quantity || 0; return <label key={branch.id}><span>{branch.shortName}</span><div className="stock-stepper"><button type="button" aria-label={"Restar un par talla " + size + " " + branch.shortName} onClick={() => setQuantity(size, branch.id, stock - 1)}>−</button><input aria-label={"Pares talla " + size + " " + branch.shortName} type="number" min="0" value={stock} onChange={(event) => setQuantity(size, branch.id, Number(event.target.value))}/><button type="button" aria-label={"Sumar un par talla " + size + " " + branch.shortName} onClick={() => setQuantity(size, branch.id, stock + 1)}>+</button></div></label>; })}<button type="button" className="size-remove" aria-label={"Quitar talla " + size} onClick={() => removeSize(size)}>×</button></div>}</article>; })}</div></fieldset>
    <section className="product-prices"><div className="product-switches"><label><input type="checkbox" checked={form.inOffer} onChange={(event) => set("inOffer", event.target.checked)}/> En oferta</label><label><input type="checkbox" checked={form.isActive} onChange={(event) => set("isActive", event.target.checked)}/> Producto activo</label></div>{form.inOffer && <div className="discount-controls"><label>Tipo de descuento<select value={form.discountType || "percentage"} onChange={(event) => set("discountType", event.target.value as DiscountType)}><option value="percentage">Porcentaje</option><option value="fixed">Cantidad fija</option></select></label><label>Valor del descuento<input type="number" min="0" max={form.discountType === "percentage" ? 100 : form.publicPrice} value={form.discountValue ?? ""} onChange={(event) => set("discountValue", Number(event.target.value))}/></label></div>}<div className="profit-preview"><p>Precio normal <strong>{money(form.publicPrice)}</strong></p>{form.inOffer && <p>Descuento <strong>{form.discountType === "percentage" ? String(form.discountValue || 0) + "%" : money(form.discountValue || 0)}</strong></p>}<p>Precio oferta <strong>{money(form.inOffer ? finalPrice : 0)}</strong></p><hr/><p>Costo <strong>{money(form.costPrice)}</strong></p><p>Utilidad normal <strong>{money(form.publicPrice - form.costPrice)}</strong></p>{form.inOffer && <p>Utilidad en oferta <strong>{money(finalPrice - form.costPrice)}</strong></p>}</div></section><button className="admin-save" disabled={uploading}>{uploading ? "Subiendo…" : editing ? "Guardar cambios" : "Guardar producto"}</button></form></section>}
  <section className="admin-product-grid">{shown.length ? shown.map((product) => { const price = product.inOffer && product.promoPrice !== null ? product.promoPrice : product.publicPrice; const pairs = product.sizes.reduce((sum, item) => sum + item.quantity, 0); return <article key={product.id} className={!product.isActive ? "inactive" : ""}><img src={product.primaryImageUrl} alt={product.name}/><div className="admin-product-body"><p>MODELO {product.model}</p><h2>{product.name || product.model}</h2><span>{product.color} · {product.sizes.map((item) => "#" + item.size + " (" + item.quantity + ")").join(" · ")}</span><small><b>Total: {pairs} pares</b></small><strong>{product.inOffer && product.promoPrice !== null ? <><del>{money(product.publicPrice)}</del> {money(price)}</> : money(price)}</strong><small>Costo {money(product.costPrice)} · Utilidad {money(price - product.costPrice)}</small><small>{product.isActive ? "Activo" : "Inactivo"}{product.inOffer ? " · En oferta" : ""}</small><div><button onClick={() => edit(product)}>Editar</button><button className="danger" onClick={() => void deactivate(product)}>Desactivar</button></div></div></article>; }) : <div className="admin-empty-products"><h2>Aún no hay productos</h2><p>Agrega el primer modelo para comenzar este catálogo.</p></div>}</section></main>;
}
