"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
type Shoe = { id: number; category: "dama" | "infantil"; title: string; caption: string; imageUrl: string };
export default function ShoeAlbumPanel() {
  const [items, setItems] = useState<Shoe[]>([]); const [notice, setNotice] = useState(""); const [uploading, setUploading] = useState(false); const [form, setForm] = useState({ category: "dama", title: "", caption: "", imageUrl: "" });
  const load = async () => { const data = await (await fetch("/api/gallery", { cache: "no-store" })).json(); setItems(data.items || []); }; useEffect(() => { void load(); }, []);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); const body = new FormData(); body.append("file", file); const response = await fetch("/api/media", { method: "POST", body }); const data = await response.json(); setUploading(false); if (!response.ok) { setNotice(data.error || "No se pudo subir la foto."); return; } setForm((current) => ({ ...current, imageUrl: data.url })); setNotice("Foto lista. Completa el nombre y agrégala al álbum."); };
  const add = async (event: FormEvent) => { event.preventDefault(); const response = await fetch("/api/gallery", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) { setNotice("Completa la categoría, el nombre y la foto."); return; } setForm({ category: "dama", title: "", caption: "", imageUrl: "" }); setNotice("Modelo agregado al álbum."); await load(); };
  const remove = async (id: number) => { await fetch(`/api/gallery?id=${id}`, { method: "DELETE" }); await load(); };
  const group = (category: "dama" | "infantil", title: string) => <section className="admin-list"><h2>{title}</h2>{items.filter((item) => item.category === category).length ? items.filter((item) => item.category === category).map((item) => <article key={item.id}><img src={item.imageUrl} alt=""/><div><strong>{item.title}</strong><p>{item.caption}</p></div><button onClick={() => void remove(item.id)}>Eliminar</button></article>) : <p>Aún no hay fotografías.</p>}</section>;
  return <main className="admin-page"><header className="admin-header"><a className="brand" href="/admin"><span>RAMBER</span><small>ÁLBUM DE CALZADO</small></a><a href="/admin">Volver al Admin</a></header><section className="admin-intro"><p className="eyebrow wine">CATÁLOGOS VISUALES</p><h1>Sube tus zapatos</h1><p>Elige dama o infantil. La foto se verá automáticamente en el álbum correspondiente de la página.</p></section>{notice && <p className="admin-notice">{notice}</p>}<section className="admin-grid"><article className="admin-card admin-wide"><h2>Agregar fotografía</h2><form onSubmit={(event) => void add(event)}><label>Sección<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}><option value="dama">Calzado para dama</option><option value="infantil">Calzado infantil</option></select></label><label>Nombre del modelo<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })}/></label><label>Pie de foto<textarea value={form.caption} onChange={(event) => setForm({ ...form, caption: event.target.value })}/></label><label>Foto<input type="file" accept="image/*" onChange={(event) => void upload(event)}/></label>{form.imageUrl && <img className="admin-preview news-preview" src={form.imageUrl} alt="Vista previa"/>}<button className="admin-save" disabled={uploading}>Agregar al álbum</button></form></article></section>{group("dama", "Álbum · Calzado para dama")}{group("infantil", "Álbum · Calzado infantil")}</main>;
}
